[package]
name = "moore-hilbert-sys"
version = "0.1.0"
authors = ["Rusty Conover <rusty@conover.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
bindgen = "0.53.2"
